### ISSUE TITLE
i18n 增加日语和繁中选项

### ISSUE THREAD

**Issue by MistEO** [MaaAssistantArknights/maa-website#15]
RT, 现在主仓库几种语言的文档都比较全了，准备找个时间往官网迁一下（

**Comment by GalvinGao** [comment]
改（

**Comment by GalvinGao** [comment]
能来一套现在GUI的多语言截图么
哦问题不大 我来吧

新GUI多语言是不是也做好了 cc—— 来点各个语言的截图——
