### ISSUE TITLE
根据文档写了个自动战斗的json，但是不起作用。

### ISSUE THREAD

**Issue by lxiaosong** [MaaAssistantArknights/maa-website#41]
`{
  "stage_name": "DC-8",
  "actions": [
    {
      "type": "SpeedUp"
    },
    {
      "type": "Deploy",
      "name": "煌",
      "location": [
        10,
        1
      ],
      "direction": "Down"
    },
    {
      "type": "Deploy",
      "name": "塞雷娅",
      "location": [
        9,
        1
      ],
      "direction": "Left"
    },
    {
      "type": "Deploy",
      "name": "鸿雪",
      "location": [
        8,
        2
      ],
      "direction": "Left"
    },
    {
      "type": "Skill",
      "name": "鸿雪"
    },
    {
      "type": "Deploy",
      "name": "打字机",
      "location": [
        4,
        4
      ],
      "direction": "Up"
    },
    {
      "type": "Deploy",
      "name": "闪灵",
      "location": [
        9,
        3
      ],
      "direction": "Up"
    },
    {
      "type": "Deploy",
      "name": "泥岩",
      "location": [
        2,
        1
      ],
      "direction": "Right",
      "post_delay": 43000
    },
    {
      "type": "Skill",
      "name": "鸿雪"
    },
    {
      "type": "Deploy",
      "name": "打字机",
      "location": [
        4,
        4
      ],
      "direction": "Up"
    },
    {
      "type": "Deploy",
      "name": "斥罪",
      "location": [
        1,
        4
      ],
      "direction": "Up",
      "post_delay": 16000
    },
    {
      "type": "Deploy",
      "name": "史尔特尔",
      "location": [
        4,
        3
      ],
      "direction": "Left",
      "post_delay": 7000
    },
    {
      "type": "Skill",
      "name": "史尔特尔"
    },
    {
      "type": "Deploy",
      "name": "马恩纳",
      "location": [
        4,
        5
      ],
      "direction": "Down",
      "post_delay": 17000
    },
    {
      "type": "Skill",
      "name": "鸿雪"
    },
    {
      "type": "Deploy",
      "name": "打字机",
      "location": [
        3,
        4
      ],
      "direction": "Down"
    }
  ],
  "opers": [
    {
      "name": "煌",
      "skill": 2,
      "skill_usage": 0
    },
    {
      "name": "史尔特尔",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "马恩纳",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "重岳",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "铎铃",
      "skill": 1,
      "skill_usage": 0
    },
    {
      "name": "泥岩",
      "skill": 2,
      "skill_usage": 0
    },
    {
      "name": "塞雷娅",
      "skill": 1,
      "skill_usage": 0
    },
    {
      "name": "斥罪",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "鸿雪",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "闪灵",
      "skill": 2,
      "skill_usage": 0
    },
    {
      "name": "焰影苇草",
      "skill": 3,
      "skill_usage": 0
    },
    {
      "name": "琴柳",
      "skill": 3,
      "skill_usage": 0
    }
  ],
  "groups": [],
  "minimum_required": "v4.10.10",
  "doc": {
    "title": "DC-8突袭简单手动",
    "details": "萧然Q（https://www.bilibili.com/video/BV1384y1p7SN?p=9&vd_source=19dd96c936bf792a1d1257b01c899f56）"
  }
}`

**Comment by ABA2396** [comment]
玛恩纳名字写错了

**Comment by MistEO** [comment]
为啥不用作业编辑器 https://prts.plus/create

**Comment by ABA2396** [comment]
![image](https://user-images.githubusercontent.com/99072975/219880857-f7c77202-1e54-4b88-857f-1961cdf777fb.png)
两个错误，
一个是 玛恩纳 写成了 马恩纳
一个是 “打字机” 写成了 打字机
